blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blogs.urls'))
]

if settings.DEBUG:
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path, include
from .views import *

app_name = 'blogs'

urlpatterns = [
    path('', Posts.as_view(), name='posts'),
    path('post/<slug:slug>/', Post.as_view(), name='post'),
    path('tags/', Tags.as_view(), name='tags'),
    path('tag/<slug:slug>/', Tag.as_view(), name='tag'),
    path('users/', include('users.urls'))
]

blogs/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField(blank=True, null=True, upload_to='tags/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:tag', kwargs={'slug': self.slug})


class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts/')
    text = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='posts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post', kwargs={'slug': self.slug})

blogs/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from blogs.models import *
from common.mixins import ViewMixin


class Posts(ListView, ViewMixin):
    model = Post
    template_name = 'blogs/posts.html'
    context_object_name = 'posts'
    active = 'posts'


class Tags(ListView, ViewMixin):
    model = Tag
    template_name = 'blogs/tags.html'
    context_object_name = 'tags'
    active = 'tags'


class Post(DetailView, ViewMixin):
    model = Post
    template_name = 'blogs/post_detail.html'
    context_object_name = 'post'
    active = 'posts'


class Tag(DetailView, ViewMixin):
    model = Tag
    template_name = 'blogs/posts.html'
    context_object_name = 'tag'
    active = 'posts'

blogs/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <a class="navbar-brand" href="#">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item {% if active == 'profile' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'blogs:users:profile' %}">My profile</a>
                        </li>
                    {% endif %}
                    <li class="nav-item {% if active == 'posts' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blogs:posts' %}">Posts</a>
                    </li>
                    <li class="nav-item {% if active == 'tags' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blogs:tags' %}">Tags</a>
                    </li>
                    <li class="nav-item {% if active == 'users' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blogs:users:users' %}">Users</a>
                    </li>
                </ul>
                {% if request.user.is_authenticated %}
                  <form class="form-inline mt-2 mt-md-0 mr-lg-5 mr-md-3">
                      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                  <span class="text-white">
                      Hello, {{ request.user.first_name }}
                      {% with photo=request.user.profile.photo %}
                          <img class="rounded-circle" width="50" height="50"
                               src="{% if photo %}{{ photo.url }}{% else %}{% static 'img/no-photo.png' %}{% endif %}"
                               alt="{{ request.user.username }}">
                      {% endwith %}
                      <a class="text-white ml-1" href="{% url 'blogs:users:logout' %}">Logout</a>
                  </span>
                {% else %}
                <ul class="navbar-nav">
                    <li class="nav-item {% if active == 'signup' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blogs:users:register' %}">Sign Up</a>
                    </li>
                    <li class="nav-item {% if active == 'signin' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'blogs:users:login' %}">Sign In</a>
                    </li>
                </ul>
                {% endif %}
              </div>
        </nav>
    </header>
    <main role="main" class="container" style="padding-top: 100px;">
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        {% block content %}{% endblock %}
    </main>

    <script>
        $(document).ready( function() {
            {% block domready %}{% endblock %}
        });
    </script>
</body>
</html>